# compose.yaml

name: JavaNumberGuess

services:
  # Gradleの初回設定用
  gradle-init:
    container_name: java_numver_guess_init

    build:
      context: .
      dockerfile: Dockerfile
      target: init

    working_dir: /workspace
    volumes:
      - .:/workspace

    stdin_open: true
    tty: true

  # アンドロイドのapkを作る用
  android:
    container_name: java_numver_guess_android

    build:
      context: .
      dockerfile: Dockerfile
      target: android

    volumes:
      - .:/workspace
